; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

; USB type "Triple Serial": provides Serial, SerialUSB1 and SerialUSB2,
; used by packetSerialA / packetSerialB in src/main.cpp
build_flags =
    -D USB_TRIPLE_SERIAL

lib_deps =
    paulstoffregen/Encoder
    frankboesing/FastCRC
    bakercp/PacketSerial


; example experiment implementations
[env:slm_aatc]
build_src_filter = +<*> -<experiments/> +<experiments/slm_aatc/>
build_flags = ${env.build_flags} -D SLM_DEBUG=1 -I src/experiments/slm_aatc

[env:ofl_shock]
build_src_filter = +<*> -<experiments/> +<experiments/ofl_shock/>
build_flags = ${env.build_flags} -I src/experiments/ofl_shock

[env:widefield_generic]
build_src_filter = +<*> -<experiments/> +<experiments/widefield_generic/>
build_flags = ${env.build_flags} -I src/experiments/widefield_generic

; template experiment implementation, for customization, make a copy of the template_experiment directory under the
; firmware/src/experiments directory and replace template_experiment in the two lines below with the name of your
; directory. See the code in the template_experiment directory for how to build a new experiment definition, or let
; `totalsync-firmware init <dir> --experiment <name>` do all of it for you.
[env:template_experiment]
build_src_filter = +<*> -<experiments/> +<experiments/template_experiment/>
build_flags = ${env.build_flags} -I src/experiments/template_experiment

