; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

; USB type "Triple Serial": provides Serial, SerialUSB1 and SerialUSB2,
; used by packetSerialA / packetSerialB in src/main.cpp
build_flags =
    -D USB_TRIPLE_SERIAL

lib_deps =
    paulstoffregen/Encoder
    frankboesing/FastCRC
    bakercp/PacketSerial

[env:slm_aatc]
build_src_filter = +<*> -<experiments/> +<experiments/slm_aatc/>
build_flags = ${env.build_flags} -D SLM_DEBUG=1 -I src/experiments/slm_aatc

[env:ofl_shock]
build_src_filter = +<*> -<experiments/> +<experiments/ofl_shock/>
build_flags = ${env.build_flags} -I src/experiments/ofl_shock

